export const TABS = {
    HOME_TAB: 'HOME_TAB',
    REWARD_TAB: 'REWARD_TAB',
    VOTE_TAB: 'VOTE_TAB',
    BARRAGE_TAB: 'BARRAGE_TAB',
};

export const ACTIONS = {
    SET_CURRENT_TAB: "SET_CURRENT_TAB",
    SET_UNREAD_MESSAGE_COUNT: "SET_UNREAD_MESSAGE_COUNT",
    ADD_BARRAGE: "ADD_BARRAGE",
    DEL_BARRAGE: "DEL_BARRAGE",
    ADD_MESSAGE: "ADD_MESSAGE"
};

